title: Apache Cordova Status
description: Badges to show all the status badges of the Apache Cordova core platforms and plugins
google_analytics: 
show_downloads: true
theme: jekyll-theme-modernist

gems:
  - jekyll-mentions
